### ISSUE TITLE
The frames per second 

### ISSUE THREAD

**Issue by peace-zy** [bertinetto/staple#1]
Hi
    I am attracted attracted by your paper. I have run the project successful. I want to know if  the ‘vot15_car1‘ sequence in code can achieve  80 frames per second ？Thank you !

**Comment by bertinetto** [comment]
Hi,
The speed has been computed by averaging the speed of all 60 vot15 sequences, on a machine with specs reported on the paper. I don't know at the moment if that car1 sequence is below or above this average.

**Comment by peace-zy** [comment]
Hi,
Thank you for you reply in time. My machine is same as the paper mentioned. The speed is 8~9 pfs. So I want to know if I do it wrong. I know the speed how to get.  If you test the ‘vot15_car1‘ sequence and get the same or different result, please tell me. Thank you!

**Comment by bertinetto** [comment]
Oh it shouldn't be that low!
Are you considering the fps with the several visualization activated? It's
extremely inefficient.

**Comment by peace-zy** [comment]
I am very sorry didn't reply in time.  The visualization is activated.  After I commented it, got the 45 fps . The result maybe reasonable

**Comment by bertinetto** [comment]
Ok that's better but it is still slower than it should be, unless that
sequence is way below average.
I am going to have a look in the next days.

**Comment by peace-zy** [comment]
OK. If you have any new progress, please tell me. Thank you!

**Comment by bertinetto** [comment]
Hi,
Sorry if it took a while but I have been quite busy recently.

I have re-run the code on our machine for all the vot15 sequences: it took 80.5 on average, but with a big variance: the slowest (_motocross2_) was 20 fps and the fastest (_soccer2_) was 120 fps.
The sample sequence I had in the repo before (_car1_) was quite below average, at 58 fps. I have uploaded one that is closer to the average of 80, so that it can be more representative of the speed of the method.
